# Will be deployed aside of the jar, to set the memory options
# for java -jar based startup via systemd EnvironmentFile
# Java 25
JAVA_TOOL_OPTIONS="-Djava.io.tmpdir=/var/weatherStation/tmp -XX:-UsePerfData -Xmx96m -Xms64m -XX:MaxMetaspaceSize=128m"
